project_id = "xyghxlddqfvcgxatbuxk"

[functions.send-contact-email]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.donation-receipt-generator]
verify_jwt = false

[functions.get-paystack-key]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false