// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyghxlddqfvcgxatbuxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Z2h4bGRkcWZ2Y2d4YXRidXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjMyODUsImV4cCI6MjA3MzU5OTI4NX0.eEsvEImMrom63FNtoMfXOWKbv8jjTi6gG_ttyCx8Ue0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});